version: '3.9'

services:
  ocp_base:
    image: ocp_base:latest
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
        OCP_COMMIT: d7d9e7b06ced339ed9de2e0d4ce4aa9c19fadc55
        CADQUERY_COMMIT: a2c1f7c4a6176ef431c1dd84170d2caebef71e8e
      target: cadquery_build
    stdin_open: true 
    tty: true

  cadquery_build:
    image: cadquery_build:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - ocp_base:latest
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.11'
        OCP_COMMIT: d7d9e7b06ced339ed9de2e0d4ce4aa9c19fadc55
        CADQUERY_COMMIT: a2c1f7c4a6176ef431c1dd84170d2caebef71e8e
      target: cadquery_build
    stdin_open: true 
    tty: true

  cadquery:
    image: szymanski2adesso/cadquery:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - cadquery_build:latest
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.11'
      target: cadquery
    stdin_open: true 
    tty: true

  cadquery-client:
    image: szymanski2adesso/cadquery-client:arm64v8
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - szymanski2adesso/cadquery:latest
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: cadquery-client
    stdin_open: true 
    tty: true

  cq-server:
    image: szymanski2adesso/cq-server:amd64
    platform: linux/amd64
    build:
      context: ./cadquery-server
      dockerfile: Dockerfile      
    command: "run"
    ports:
      - "5050:5000"