version: '3.9'

services:
  ocp_base:
    image: ocp_base:latest
    build:
      context: .
      dockerfile: Dockerfile
      #cache_from: 
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
        OCP_COMMIT: 6b7b7325ab4599a8ba9049f176f099574fe64dfc
        CADQUERY_COMMIT: 4c6f968ac1e411a53d20779309778e1b4a585fa3
      target: cadquery_build
    stdin_open: true 
    tty: true

  cadquery_build:
    image: cadquery_build:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - ocp_base:latest
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
        OCP_COMMIT: 6b7b7325ab4599a8ba9049f176f099574fe64dfc
        CADQUERY_COMMIT: 4c6f968ac1e411a53d20779309778e1b4a585fa3
      target: cadquery_build
    stdin_open: true 
    tty: true

  cadquery:
    image: szymanski2adesso/cadquery:latest
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: cadquery
    stdin_open: true 
    tty: true

  cq-client:
    image: szymanski2adesso/cadquery-client:arm64v8
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: cadquery-client
    stdin_open: true 
    tty: true

  cq-server:
    image: szymanski2adesso/cq-server:amd64
    platform: linux/amd64
    build:
      context: ./cadquery-server
      dockerfile: Dockerfile      
    command: "run"
    ports:
      - "5050:5000"