version: '3.9'

services:
  ocp_base:
    image: ocp/base:ocp_base
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        ARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: ocp_base
    stdin_open: true 
    tty: true

  ocp_build:
    image: ocp/base:ocp_build
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        ARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: ocp_build
    stdin_open: true 
    tty: true

    
  ocp_compiler_base:
    image: ocp/base:ocp_compiler_base
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        ARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: ocp_compiler_base
    stdin_open: true 
    tty: true

  ocp_build_conda_package:
    image: ocp/base:ocp_build_conda_package
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        ARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: build_conda_package
    stdin_open: true 
    tty: true

  cadquery_build_base:
    image: cadquery/base:cadquery_build_base
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        ARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: cadquery_build_base
    stdin_open: true 
    tty: true

  cadquery:
    image: cadquery:cadquery_root
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        ARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: cadquery_root
    volumes:
      - ./data:/home/cadquery/data
    stdin_open: true 
    tty: true

  cadquery_dockerhub:
    image: szymanski2adesso/cadquery:latest
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        ARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: cadquery
    stdin_open: true 
    tty: true

  cadquery-client:
    image: szymanski2adesso/cadquery-client:arm64v8
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        ARCH: arm64v8
        PYTHON_VERSION: '3.9'
        ANACONDA3_VERSION: '2022.10'
      target: cadquery-client
    stdin_open: true 
    tty: true

  cq-server:
    image: szymanski2adesso/cq-server:amd64
    platform: linux/amd64
    build:
      context: ./cadquery-server
      dockerfile: Dockerfile      
    command: "run"
    ports:
      - "5050:5000"