version: '3.9'

services:
  ocp_base:
    image: ocp_base:latest
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.11'
        ANACONDA3_VERSION: '2023.09-0'
        OCP_COMMIT: occt772
        CADQUERY_COMMIT: '2.4.0'
        EZDXF_TAG: 'v1.1.4'
      target: cadquery_build
    stdin_open: true 
    tty: true

  cadquery_build:
    image: cadquery_build:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - ocp_base:latest
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.11'
        ANACONDA3_VERSION: '2023.09-0'
        OCP_COMMIT: occt772
        CADQUERY_COMMIT: '2.4.0'
        EZDXF_TAG: 'v1.1.4'
      target: cadquery_build
    stdin_open: true 
    tty: true

  cadquery:
    image: szymanski2adesso/cadquery:2.4.0
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - cadquery_build:latest
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.11'
        ANACONDA3_VERSION: '2023.09-0'
        OCP_COMMIT: occt772
        CADQUERY_COMMIT: '2.4.0'
        EZDXF_TAG: 'v1.1.4'
      target: cadquery
    stdin_open: true 
    tty: true

  cadquery-client:
    image: szymanski2adesso/cadquery-client:2.4.0
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - szymanski2adesso/cadquery:2.4.0
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.11'
        ANACONDA3_VERSION: '2023.09-0'
        OCP_COMMIT: occt772
        CADQUERY_COMMIT: '2.4.0'
        EZDXF_TAG: 'v1.1.4'
      target: cadquery-client
    stdin_open: true 
    tty: true
    entrypoint: ["/bin/bash"]

  cq-server:
    image: szymanski2adesso/cq-server:amd64
    platform: linux/amd64
    build:
      context: ./cadquery-server
      dockerfile: Dockerfile      
    command: "run"
    ports:
      - "5050:5000"

  cadquery-runtime:
    image: szymanski2adesso/cadquery-runtime:2.4.0
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - szymanski2adesso/cadquery:2.4.0
      args: 
        TARGETARCH: arm64v8
        PYTHON_VERSION: '3.11'
        ANACONDA3_VERSION: '2023.09-0'
        OCP_COMMIT: occt772
        CADQUERY_COMMIT: '2.4.0'
        EZDXF_TAG: 'v1.1.4'
      target: runtime
    stdin_open: true 
    tty: true
    entrypoint: ["source /venv/bin/activate"]